image: docker:stable
services:
 - docker:dind

stages:
 - commit-stage
 - manual-test
 - security
 - deploy

commit-stage:
 only:
   - master
 stage: commit-stage
 script:
   - echo "running build..."
   - return 1

unit-test:
 only:
   - master
 stage: commit-stage
 script:
   - echo "running unit tests.."

publishToDev:
 only:
   - master
 stage: manual-test
 script:
   - echo "I'm the test stage"

security-stage:
 only:
   - master
 stage: security
 script:
   - echo "Security stage. you're welcome Tim"

publishToProd:
 only:
   - master
 stage: deploy
 script:
   - echo "I'm deploying now"
 when: manual
