image: alpine

stages:
 - commit
 - aat-preprod
 - uat-preprod
 - nfr-tests
 - create-rfc  
 - deploy-to-prod
 - close-rfc

commit:
 only:
   - master
 stage: commit
 script:
   - echo "Running build..."
   - echo "Running unit tests"
   - echo "Publishing to artifactory"

aat-preprod:
 only:
   - master
 stage: aat-preprod
 script:
   - echo "Deploying to preprod..."
   - echo "Running AAT..."

uat-preprod:
 only:
   - master
 stage: uat-preprod
 script:
   - echo "Running UAT..."
 when: manual

performance-test:
 only:
   - master
 stage: nfr-tests
 script:
   - echo "Deploying to preprod..."
   - echo "Running load tests..."
 
capacity-test:
 only:
   - master
 stage: nfr-tests
 script:
   - echo "Deploying to preprod..."
   - echo "Running load tests..."

security-scan:
 only:
   - master
 stage: nfr-tests
 script:
   - echo "Deploying to preprod..."
   - echo "Running security scan..."

rfc-create:
 only:
   - master
 stage: create-rfc
 script:
   - echo "Waiting for RFC to be created..."
 when: manual

deploy-to-prod:
 only:
   - master
 stage: deploy-to-prod
 script:
   - echo "Deploy to prod..."
   - echo "Run smoke test..."
   - echo "Send slack notification"

close-rfc:
 only:
   - master
 stage: close-rfc
 script:
   - echo "Closing RFC..."
