image: alpine

stages:
 - build
 - unit-test
 - publish
 - deploy-to-sandbox
 - functional-tests-sandbox
 - deploy-to-prerod
 - functional-tests-preprod
 - performance-tests
 - security
 - create-rfc
 - deploy-to-prod
 - smoke-test
 - close-rfc

build:
 only:
   - master
 stage: build
 script:
   - echo "Running build..."

unit-test:
 only:
   - master
 stage: unit-test
 script:
   - echo "Running unit tests.."

publish:
 only:
   - master
 stage: publish
 script:
   - echo "Publishing to artifactory"

deploy-to-sandbox:
 only:
   - master
 stage: deploy-to-sandbox
 script:
   - echo "Deploying to sandbox"

functional-tests-sandbox:
 only:
   - master
 stage: functional-tests-sandbox
 script:
   - echo "Running functional tests against sandbox"

deploy-to-prerod:
 only:
   - master
 stage: deploy-to-prerod
 script:
   - echo "Deploying to preprod"

functional-tests-preprod:
 only:
   - master
 stage: functional-tests-preprod
 script:
   - echo "Running functional tests against preprod"

load-tests:
 only:
   - master
 stage: performance-tests
 script:
   - echo "Running load tests"

capacity-tests:
 only:
   - master
 stage: performance-tests
 script:
   - echo "Running capacity tests"

security:
 only:
   - master
 stage: security
 script:
   - echo "Running security scan"

create-rfc:
 only:
   - master
 stage: deploy-to-prod
 script:
   - echo "Waiting for RFC creation"
 when: manual

deploy-to-prod:
 only:
   - master
 stage: deploy-to-prod
 script:
   - echo "Deploying to production"

smoke-test:
 only:
   - master
 stage: smoke-test
 script:
   - echo "Running smoke test against prod"

close-rfc:
 only:
   - master
 stage: close-rfc
 script:
   - echo "Closing RFC"
